# @package inspire

xml: assets/robots/g1_inspire/scene.xml

sim:
  stiffness: 5
  damping: 0.5
  torque_limit: 1

dof:
  joint_names:
    - R_pinky_proximal_joint
    - R_ring_proximal_joint
    - R_middle_proximal_joint
    - R_index_proximal_joint
    - R_thumb_proximal_pitch_joint
    - R_thumb_proximal_yaw_joint
    - L_pinky_proximal_joint
    - L_ring_proximal_joint
    - L_middle_proximal_joint
    - L_index_proximal_joint
    - L_thumb_proximal_pitch_joint
    - L_thumb_proximal_yaw_joint
  lower:
    - 0
    - 0
    - 0
    - 0
    - -0.1
    - -0.1
    - 0
    - 0
    - 0
    - 0
    - -0.1
    - -0.1
  upper:
    - 1.7
    - 1.7
    - 1.7
    - 1.7
    - 0.6
    - 1.3
    - 1.7
    - 1.7
    - 1.7
    - 1.7
    - 0.6
    - 1.3

mimic:
  L_index_intermediate_joint:
    driver: L_index_proximal_joint
    multiplier: 1
    offset: 0
    lower: 0
    upper: 1.7
  L_middle_intermediate_joint:
    driver: L_middle_proximal_joint
    multiplier: 1
    offset: 0
    lower: 0
    upper: 1.7
  L_pinky_intermediate_joint:
    driver: L_pinky_proximal_joint
    multiplier: 1
    offset: 0
    lower: 0
    upper: 1.7
  L_ring_intermediate_joint:
    driver: L_ring_proximal_joint
    multiplier: 1
    offset: 0
    lower: 0
    upper: 1.7
  L_thumb_distal_joint:
    driver: L_thumb_proximal_pitch_joint
    multiplier: 2.4
    offset: 0
    lower: 0
    upper: 1.2
  L_thumb_intermediate_joint:
    driver: L_thumb_proximal_pitch_joint
    multiplier: 1.6
    offset: 0
    lower: 0
    upper: 0.8
  R_index_intermediate_joint:
    driver: R_index_proximal_joint
    multiplier: 1
    offset: 0
    lower: 0
    upper: 1.7
  R_middle_intermediate_joint:
    driver: R_middle_proximal_joint
    multiplier: 1
    offset: 0
    lower: 0
    upper: 1.7
  R_pinky_intermediate_joint:
    driver: R_pinky_proximal_joint
    multiplier: 1
    offset: 0
    lower: 0
    upper: 1.7
  R_ring_intermediate_joint:
    driver: R_ring_proximal_joint
    multiplier: 1
    offset: 0
    lower: 0
    upper: 1.7
  R_thumb_distal_joint:
    driver: R_thumb_proximal_pitch_joint
    multiplier: 2.4
    offset: 0
    lower: 0
    upper: 1.2
  R_thumb_intermediate_joint:
    driver: R_thumb_proximal_pitch_joint
    multiplier: 1.6
    offset: 0
    lower: 0
    upper: 0.8
