# @package policy

policy_file: assets/models/g1/unitree/policy_wo_gait.pt
dof:
  joint_names:
    - left_hip_pitch_joint
    - right_hip_pitch_joint
    - waist_yaw_joint
    - left_hip_roll_joint
    - right_hip_roll_joint
    - waist_roll_joint
    - left_hip_yaw_joint
    - right_hip_yaw_joint
    - waist_pitch_joint
    - left_knee_joint
    - right_knee_joint
    - left_shoulder_pitch_joint
    - right_shoulder_pitch_joint
    - left_ankle_pitch_joint
    - right_ankle_pitch_joint
    - left_shoulder_roll_joint
    - right_shoulder_roll_joint
    - left_ankle_roll_joint
    - right_ankle_roll_joint
    - left_shoulder_yaw_joint
    - right_shoulder_yaw_joint
    - left_elbow_joint
    - right_elbow_joint
    - left_wrist_roll_joint
    - right_wrist_roll_joint
    - left_wrist_pitch_joint
    - right_wrist_pitch_joint
    - left_wrist_yaw_joint
    - right_wrist_yaw_joint
  default_pos:
    - -0.1
    - -0.1
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.3
    - 0.3
    - 0.3
    - 0.3
    - -0.2
    - -0.2
    - 0.25
    - -0.25
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.97
    - 0.97
    - 0.15
    - -0.15
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  stiffness:
    - 100.0
    - 100.0
    - 200.0
    - 100.0
    - 100.0
    - 40.0
    - 100.0
    - 100.0
    - 40.0
    - 150.0
    - 150.0
    - 40.0
    - 40.0
    - 40.0
    - 40.0
    - 40.0
    - 40.0
    - 40.0
    - 40.0
    - 40.0
    - 40.0
    - 40.0
    - 40.0
    - 40.0
    - 40.0
    - 40.0
    - 40.0
    - 40.0
    - 40.0
  damping:
    - 2.0
    - 2.0
    - 5.0
    - 2.0
    - 2.0
    - 5.0
    - 2.0
    - 2.0
    - 5.0
    - 4.0
    - 4.0
    - 10.0
    - 10.0
    - 2.0
    - 2.0
    - 10.0
    - 10.0
    - 2.0
    - 2.0
    - 10.0
    - 10.0
    - 10.0
    - 10.0
    - 10.0
    - 10.0
    - 10.0
    - 10.0
    - 10.0
    - 10.0
action_scale: 0.25
obs_scales:
  ang_vel: 0.2
  dof_vel: 0.05
max_cmd: [0.8, 0.5, 1.57]
