frequency: 50
observation:
  joint_names:
    - left_hip_pitch_joint
    - right_hip_pitch_joint
    - waist_yaw_joint
    - left_hip_roll_joint
    - right_hip_roll_joint
    - waist_roll_joint
    - left_hip_yaw_joint
    - right_hip_yaw_joint
    - waist_pitch_joint
    - left_knee_joint
    - right_knee_joint
    - left_shoulder_pitch_joint
    - right_shoulder_pitch_joint
    - left_ankle_pitch_joint
    - right_ankle_pitch_joint
    - left_shoulder_roll_joint
    - right_shoulder_roll_joint
    - left_ankle_roll_joint
    - right_ankle_roll_joint
    - left_shoulder_yaw_joint
    - right_shoulder_yaw_joint
    - left_elbow_joint
    - right_elbow_joint
    - left_wrist_roll_joint
    - right_wrist_roll_joint
    - left_wrist_pitch_joint
    - right_wrist_pitch_joint
    - left_wrist_yaw_joint
    - right_wrist_yaw_joint
    - L_index_proximal_joint
    - L_middle_proximal_joint
    - L_pinky_proximal_joint
    - L_ring_proximal_joint
    - L_thumb_proximal_yaw_joint
    - R_index_proximal_joint
    - R_middle_proximal_joint
    - R_pinky_proximal_joint
    - R_ring_proximal_joint
    - R_thumb_proximal_yaw_joint
    - L_index_intermediate_joint
    - L_middle_intermediate_joint
    - L_pinky_intermediate_joint
    - L_ring_intermediate_joint
    - L_thumb_proximal_pitch_joint
    - R_index_intermediate_joint
    - R_middle_intermediate_joint
    - R_pinky_intermediate_joint
    - R_ring_intermediate_joint
    - R_thumb_proximal_pitch_joint
    - L_thumb_intermediate_joint
    - R_thumb_intermediate_joint
    - L_thumb_distal_joint
    - R_thumb_distal_joint
  default_joint_pos:
    - -0.312
    - -0.312
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.669
    - 0.669
    - 0.2
    - 0.2
    - -0.363
    - -0.363
    - 0.2
    - -0.2
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.6
    - 0.6
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  future_offsets:
    - 0
    - 5
    - 10
    - 15
    - 20
  anchor_body: pelvis
action:
  body:
    joint_names:
      - left_hip_pitch_joint
      - right_hip_pitch_joint
      - waist_yaw_joint
      - left_hip_roll_joint
      - right_hip_roll_joint
      - waist_roll_joint
      - left_hip_yaw_joint
      - right_hip_yaw_joint
      - waist_pitch_joint
      - left_knee_joint
      - right_knee_joint
      - left_shoulder_pitch_joint
      - right_shoulder_pitch_joint
      - left_ankle_pitch_joint
      - right_ankle_pitch_joint
      - left_shoulder_roll_joint
      - right_shoulder_roll_joint
      - left_ankle_roll_joint
      - right_ankle_roll_joint
      - left_shoulder_yaw_joint
      - right_shoulder_yaw_joint
      - left_elbow_joint
      - right_elbow_joint
      - left_wrist_roll_joint
      - right_wrist_roll_joint
      - left_wrist_pitch_joint
      - right_wrist_pitch_joint
      - left_wrist_yaw_joint
      - right_wrist_yaw_joint
    control:
      stiffness:
        - 40.1792
        - 40.1792
        - 40.1792
        - 99.0984
        - 99.0984
        - 28.5012
        - 40.1792
        - 40.1792
        - 28.5012
        - 99.0984
        - 99.0984
        - 14.2506
        - 14.2506
        - 28.5012
        - 28.5012
        - 14.2506
        - 14.2506
        - 28.5012
        - 28.5012
        - 14.2506
        - 14.2506
        - 14.2506
        - 14.2506
        - 14.2506
        - 14.2506
        - 16.7783
        - 16.7783
        - 16.7783
        - 16.7783
      damping:
        - 2.5579
        - 2.5579
        - 2.5579
        - 6.3088
        - 6.3088
        - 1.8144
        - 2.5579
        - 2.5579
        - 1.8144
        - 6.3088
        - 6.3088
        - 0.9072
        - 0.9072
        - 1.8144
        - 1.8144
        - 0.9072
        - 0.9072
        - 1.8144
        - 1.8144
        - 0.9072
        - 0.9072
        - 0.9072
        - 0.9072
        - 0.9072
        - 0.9072
        - 1.0681
        - 1.0681
        - 1.0681
        - 1.0681
  hand:
    joint_names:
      - L_index_proximal_joint
      - L_middle_proximal_joint
      - L_pinky_proximal_joint
      - L_ring_proximal_joint
      - L_thumb_proximal_yaw_joint
      - R_index_proximal_joint
      - R_middle_proximal_joint
      - R_pinky_proximal_joint
      - R_ring_proximal_joint
      - R_thumb_proximal_yaw_joint
      - L_thumb_proximal_pitch_joint
      - R_thumb_proximal_pitch_joint
  scale:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
  offset:
    - -0.312
    - -0.312
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.669
    - 0.669
    - 0.2
    - 0.2
    - -0.363
    - -0.363
    - 0.2
    - -0.2
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.6
    - 0.6
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
