defaults:
  - robot: g1
  - policy: body_hand_distill_largebox
  - deployment: sim
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_

motion:
  file: assets/motions/largebox_v02.npz
  name: sub16_largebox_013_v02

startup:
  ramp_seconds: 3.0
  blend_seconds: 5.0

recording:
  enabled: true
  directory: logs

env:
  _target_: g1_playground.g1_env.G1Env

hydra:
  job:
    chdir: false
  output_subdir: null
  run:
    dir: .
