defaults:
  - robot: g1
  - robot@inspire: inspire
  - policy@loco: leggedlab_g1
  - policy@hoi: body_hand_distill_largebox
  - policy@track: track
  - deployment: sim
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_

motion:
  file: assets/motions/clothesstand_v02.npz
  name: null

startup:
  ramp_seconds: 3.0

handover:
  to_hoi_seconds: 2.0
  to_default_seconds: 5.0

recording:
  enabled: true
  seconds: 1200
  directory: logs

env:
  _target_: g1_playground.g1_env.G1Env

hydra:
  job:
    chdir: false
  output_subdir: null
  run:
    dir: .
