defaults:
  - robot: g1
  - policy@loco: leggedlab_g1
  - policy@track: track
  - deployment: sim
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_

device: cpu

recording:
  enabled: false
  seconds: 1200
  directory: logs

handover:
  crossfade_seconds: 2.0
  rate_limit: 0.05

env:
  _target_: g1_playground.g1_env.G1Env

hydra:
  job:
    chdir: false
  output_subdir: null
  run:
    dir: .
