defaults:
  - dds: sim
  - _self_

hydra:
  output_subdir: null
  run:
    dir: .

policy:
  model: models/locomotion/policy_wo_gait.onnx

  command:
    vx: 0.0
    vy: 0.0
    wyaw: 0.0

  policy_joint_order: bfs

  obs_scales:
    ang_vel: 0.2
    dof_vel: 0.05
  history_length: 5

  max_cmd: [0.8, 0.5, 1.57]

  action_scale:
    default: 0.25

  default_pos:  # rad
    default: 0.0
    values:
      ".*_hip_pitch_joint": -0.1
      ".*_knee_joint": 0.3
      ".*_ankle_pitch_joint": -0.2
      ".*_shoulder_pitch_joint": 0.3
      "left_shoulder_roll_joint": 0.25
      "right_shoulder_roll_joint": -0.25
      ".*_elbow_joint": 0.97
      "left_wrist_roll_joint": 0.15
      "right_wrist_roll_joint": -0.15

  kp:  # N·m/rad
    default: 40.0
    values:
      ".*_hip_.*_joint": 100.0
      "waist_yaw_joint": 200.0
      ".*_knee_joint": 150.0

  kd:  # N·m·s/rad
    default: 10.0
    values:
      ".*_hip_.*_joint": 2.0
      "waist_.*_joint": 5.0
      ".*_knee_joint": 4.0
      ".*_ankle_.*_joint": 2.0
