# @package _global_

inspire_service: true
inspire_serial:
  left: /dev/serial/by-path/platform-3610000.usb-usb-0:2.1.2:1.0-port0
  right: /dev/serial/by-path/platform-3610000.usb-usb-0:2.1.4:1.0-port0

env:
  domain_id: 0
  net_if: enP8p1s0
  lowcmd_topic: rt/lowcmd
  lowstate_topic: rt/lowstate
  enable_odometry: true
  sport_state_topic: rt/odommodestate
  motion_switcher_required: true

controller:
  _target_: g1_playground.controller.unitree_ctrl.UnitreeCtrl
