# @package _global_

inspire_service: false

env:
  domain_id: 1
  net_if: lo
  lowcmd_topic: rt/lowcmd
  lowstate_topic: rt/lowstate
  enable_odometry: true
  sport_state_topic: rt/odommodestate
  motion_switcher_required: false

controller:
  _target_: g1_playground.controller.keyboard_ctrl.KeyboardCtrl
  forward_axis: 0.5
  backward_axis: 0.5
  strafe_axis: 0.4
  turn_axis: 0.35
  stale_timeout: 0.2

sim_odometry:
  publish_hz: 50.0
